### ISSUE TITLE
ValueError: cannot reshape array of size 2457600 into shape

### ISSUE THREAD

**Issue by johnpaulbin** [NTT123/hifigan-tpu#1]
Hi, after following the steps provided in the README, I was presented with this error:

```
  File "train.py", line 258, in load_data
    y = y.reshape((num_devices, spu, -1, *y.shape[1:]))
ValueError: cannot reshape array of size 2457600 into shape (8,40,newaxis,15360)
```

Full log:

`!python3 train.py --data-dir=/content/hifigan-tpu/wavs`

```
2022-04-16 22:07:58.972010: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-04-16 22:08:21.282661: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Data set size: 4788 batches
8 devices: [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0), TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1), TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0), TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1), TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0), TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1), TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0), TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
Traceback (most recent call last):
  File "train.py", line 440, in <module>
    fire.Fire(train)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "train.py", line 378, in train
    batch = next(train_data_iter)
  File "train.py", line 176, in double_buffer
    for next_batch in ds:
  File "train.py", line 258, in load_data
    y = y.reshape((num_devices, spu, -1, *y.shape[1:]))
ValueError: cannot reshape array of size 2457600 into shape (8,40,newaxis,15360)
```

**Comment by johnpaulbin** [comment]
Problem should solved after satisfying this line inside train.py:

`if len(batch) == config.batch_size * spu:`

But I cannot figure out the correct SPU & batch size

(I'm using v2 config)

**Comment by NTT123** [comment]
Hi @johnpaulbin, a few notes:

1. if you are running on google colab TPUv2, please try to add `--spu=1` in your command line. Using spu=1 is needed to avoid compilation error with TPUv2.
2. each mini-batch returned from the `load_data` function is *actually* `spu` batches. This is needed because we are running `spu` training steps per TPU call for better performance.
3. `config.batch_size` should be divisible by number of devices (8 in your case).

**Comment by johnpaulbin** [comment]
Works great now, thanks for the assistance!
